CREATE TABLE "users" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(30) NOT NULL,
  "email" varchar(50) NOT NULL,
  "password" varchar(30) NOT NULL,
  "age" int NOT NULL,
  "role_id" int NOT NULL
);

CREATE TABLE "roles" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(30) NOT NULL
);

CREATE TABLE "categories" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar NOT NULL
);

CREATE TABLE "levels_categorie" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(30)
);

CREATE TABLE "courses" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" varchar(30) NOT NULL,
  "description" varchar(60),
  "levelcat_id" int NOT NULL,
  "teacher" int NOT NULL,
  "categorie_id" int NOT NULL
);

CREATE TABLE "courses_video" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" varchar(30),
  "url" varchar,
  "course_id" int NOT NULL
);

CREATE TABLE "users_courses" (
  "user_id" int NOT NULL,
  "course_id" int NOT NULL
);

ALTER TABLE "courses_video" ADD FOREIGN KEY ("course_id") REFERENCES "courses" ("id");

ALTER TABLE "courses" ADD FOREIGN KEY ("categorie_id") REFERENCES "categories" ("id");

ALTER TABLE "courses" ADD FOREIGN KEY ("levelcat_id") REFERENCES "levels_categorie" ("id");

ALTER TABLE "users" ADD FOREIGN KEY ("role_id") REFERENCES "roles" ("id");

ALTER TABLE "users_courses" ADD FOREIGN KEY ("course_id") REFERENCES "courses" ("id");

ALTER TABLE "users_courses" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "courses" ADD FOREIGN KEY ("teacher") REFERENCES "users" ("id");

INSERT INTO roles (name) VALUES ('students'), ('teacher'), ('admin');

INSERT INTO users (name, email, password, age, role_id) VALUES ('Aldo Campos', 'aldo@gmail.com', '123456a', 28, 1);

INSERT INTO users (name, email, password, age, role_id) VALUES ('Ian Rosas', 'rosasI@gmail.com', '123456ais', 33, 2);

INSERT INTO users (name, email, password, age, role_id) VALUES ('Benjamin Flores', 'benF@gmail.com', 'flores48757', 32, 2);

INSERT INTO categories (name) VALUES ('front-end development'), ('back-end development'), ('digital marketing');

INSERT INTO levels_categorie (name) VALUES ('beginner'), ('intermediate'), ('advance');

INSERT INTO courses (title, description, levelcat_id, teacher, categorie_id) VALUES ('javascript', 'aprenderas javascript desde cero', 1, 3, 1), ('node js', 'aprenderas a crear apis desde cero', 1, 2, 2);

INSERT INTO courses_video (title, url, course_id) VALUES ('tipo de datos y funciones', 'https://google.com', 1),  ('bases de datos y express', 'https://youtube.com', 2);

INSERT INTO users_courses (user_id, course_id) VALUES (1, 1), (1, 2);

